version: '3.1'

services:
    cloudbeaver:
        container_name: cloudbeaver-server
        image: dbeaver/cloudbeaver:23.1.3
        ports:
            - 8080:8978
        networks:
            analytics:
                ipv4_address: 172.10.1.10
        restart: always
        volumes:
            - ./cb_workspace:/opt/cloudbeaver/workspace
        depends_on:
            - db

    db:
        container_name: mysql-server
        image: mysql
        ports:
            - 3306:3306
        networks:
            analytics:
                ipv4_address: 172.10.1.20
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: analytics_db
            MAX_ALLOWED_PACKET: 1073741824
        volumes:
            - ./mysql:/var/lib/mysql
            - ./init_db:/docker-entrypoint-initdb.d

networks:
  analytics:
    driver: bridge
    ipam:
        driver: default
        config: 
            - subnet: 172.10.1.0/24